-- Superseded: project switched to SQLite. Schema is applied via `prisma db push`.
-- This Postgres migration is intentionally a no-op. To recreate clean SQLite migration
-- history, delete the prisma/migrations folder and run `prisma migrate dev --name init`.
